In [6]:
import numpy as np
import pandas as pd

In [7]:
emnist_train = pd.read_csv("/Users/jaladisaran/Downloads/emnist-letters-train.csv")
emnist_test = pd.read_csv("/Users/jaladisaran/Downloads/emnist-letters-test.csv")

In [56]:
emnist_train

,23,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.406,0.407,0.408,0.409,0.410,0.411,0.412,0.413,0.414,0.415
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,16,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,15,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88794,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88795,21,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88796,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88797,23,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
88798,12,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [57]:
emnist_test

,1,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.548,0.549,0.550,0.551,0.552,0.553,0.554,0.555,0.556,0.557
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14794,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14795,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14796,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14797,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14798,19,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
train = emnist_train.to_numpy()
test = emnist_test.to_numpy()

In [59]:
train

array([[ 7,  0,  0, ...,  0,  0,  0],
       [16,  0,  0, ...,  0,  0,  0],
       [15,  0,  0, ...,  0,  0,  0],
       ...,
       [ 1,  0,  0, ...,  0,  0,  0],
       [23,  0,  0, ...,  0,  0,  0],
       [12,  0,  0, ...,  0,  0,  0]])

In [60]:
train[:,1:].shape

(88799, 784)

In [61]:
X_train = train[:,1:]
X_test = test[:,1:]

In [62]:
train[:,0]

array([ 7, 16, 15, ...,  1, 23, 12])

In [74]:
Y_train = train[:,0]
Y_test = test[:,0]
Y_train

array([ 7, 16, 15, ...,  1, 23, 12])

In [64]:
X_train=X_train/255
X_test=X_test/255

In [65]:
def function(X,W,b):
    f = np.dot(X,W)+b
    return f
def err(X,Y,W,b):
    err = function(X,W,b)-Y
    return err

In [66]:
def cost_function(X,Y,W,b):
    m = X.shape[0]
    cost = np.dot(err(X,Y,W,b),err(X,Y,W,b))
    cost = cost/(2*m)
    return cost
def gradient_compute(X,Y,W,b):
    m=X.shape[0]
    dj_dw = np.dot(err(X,Y,W,b),X)
    dj_dw = dj_dw/m
    
    dj_db = np.sum(err(X,Y,W,b))/m
    
    return dj_dw,dj_db

In [67]:
def gradient_descent(X,Y,W,b,L,n):
    m=X.shape[0]
    
    for i in range(n):
        dj_dw = gradient_compute(X,Y,W,b)[0]
        dj_db = gradient_compute(X,Y,W,b)[1]
        W=W-L*dj_dw
        b=b-L*dj_db
        cost = cost_function(X,Y,W,b)
        
        
    return W,b,cost

In [96]:
w=np.zeros(X_train.shape[1])
b=0
n=1000
L=0.04
w_final,b_final,cost = gradient_descent(X_train,Y_train,w,b,L,n)
cost

20.371378511660872

In [106]:
Y_output = function(X_test,w_final,b_final)
Y_output = np.rint(y_output)

In [107]:
def accuracy(yout,ytest):
    m = yout.shape[0]
    count=0
    for i in range(m):
        if yout[i]==ytest[i]:
            count+=1
            
    acc = count/m*100
    return acc

In [108]:
accuracy(Y_output,Y_test)

6.189607405905805